defaults:
  - _self_
  - data@__global__: human_eval

device: "0"
output_path: "results/qwen2p5-7b"

layers: [21, 22, 23, 24, 25, 26]
latent_type: "hidden"

model_path: "Qwen/Qwen2.5-Coder-7B-Instruct"
model_type: "qwen"


